### ISSUE TITLE
Question(s)

### ISSUE THREAD

**Issue by Fireworkstars46** [JewishBanana/DeadlyDisasters#4]
I have a question about this plugin

**Comment by stabaho** [comment]
This is the place for your questions. You have to actually ask it though.

**Comment by Fireworkstars46** [comment]
As for the tornadoes in it, is there a setting or option to edit what it does? Like pickup specific blocks etc?

**Comment by stabaho** [comment]
Most support comes from discord. Join here: https://discord.gg/5uM9MRvfWv

**Comment by JewishBanana** [comment]
> As for the tornadoes in it, is there a setting or option to edit what it does? Like pickup specific blocks etc?

You can blacklist blocks or if you create a custom disaster and spawn a tornado you can modify what blocks it will be made of.
