### ISSUE TITLE
Console error spam when a disaster starts

### ISSUE THREAD

**Issue by Nobookie** [JewishBanana/DeadlyDisasters#6]
My server console keeps being spammed with those error messages
![image](https://github.com/JewishBanana/DeadlyDisasters/assets/31146142/e0de2d8f-e1ea-46d7-af79-3bfc6fe946eb)

**Comment by Nobookie** [comment]
I'm running Purpur #2176 (MC 1.20.4)
![image](https://github.com/JewishBanana/DeadlyDisasters/assets/31146142/94ef1264-99b5-48a2-8f37-d959f1315255)

**Comment by JewishBanana** [comment]
Thnx
